# Generated by Django 2.1.5 on 2019-01-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
