# Generated by Django 2.1.5 on 2019-02-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190131_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimeo_link',
            name='video',
            field=models.URLField(),
        ),
    ]
