# Generated by Django 2.1.5 on 2019-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
