# Generated by Django 2.1.5 on 2019-02-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('business_address', models.CharField(max_length=30)),
                ('about_me', models.TextField(max_length=1000)),
            ],
        ),
    ]
